### ISSUE TITLE
Double Listing Of Attribute Titles (Mixed Failure)

### ISSUE THREAD

**Issue by Host99** [potteryhouse/stock_by_attribute_1.5.4#21]
![weird_listing_combos](https://cloud.githubusercontent.com/assets/6235393/5567732/aab70bb4-8f18-11e4-91a0-14a5ab1da391.JPG)
![admin](https://cloud.githubusercontent.com/assets/6235393/5567737/be34dd2e-8f18-11e4-806f-0090e5394cca.JPG)

There is some crazy listings on the customer side. See images. They should not be listed like this and should be separated. Anyway to do this where it list one size one flavor together and not a bunch of the same thing? The way it is now, it is very confusing and to fix it as current we would have to create complete separate products, which we want to avoid.

We contributed to the first version of this with the custom ids. We would help again if this can be done. Any help is appreciated.

**Comment by jeking928** [comment]
I'm seeing what appears to be related to the same issue.  On a stock 1.5.3 cart, I've setup mixed attributes.  One the storefront, they are being displayed incorrectly. See images below.
![image](https://cloud.githubusercontent.com/assets/8162029/5787314/1e33a836-9dbf-11e4-834b-bcd5bc5fd659.png)

![image](https://cloud.githubusercontent.com/assets/8162029/5787311/0ed072e8-9dbf-11e4-93ea-49b4e07e053d.png)

**Comment by mc12345678** [comment]
Have consistently seen this issue for a while now, still looking into how to resolve it without adding dynamic dropdowns (which does resolve this duplication issue at least in the mc12345678 branches.) Only seems to appear when multiple attributes are provided. Haven't tried adding product that has multiple independent attributes (if that is even supported yet) ie. Where there are x product with memory and y product of a model, but no such z quantity of model with this much memory.

**Comment by mc12345678** [comment]
Believe it or not, the real problem in this situation is/was not the duplication, but actually the lack of duplication...

So, welcome to the historical problems of SBA with multiple attributes. Here is where decisions/functions/options get added to accomodate various options.
1) Only selectable attributes regardless of currently available quantity are presented (no javascript/ajax or whatever calls are needed.) Plain and simple the things that can be selected are presented for selection. Availability identified upon trying to add to the cart. Problems seen with this are in relation to using other plugins like where search engines are provided availability information of product. In this situation the currently provided maximum (accumulative quantity) of product may be an indicator that something exists related to the product, but wouldn't necessarily identify all the available options. A minor issue currently, but could see as such reporting tools become more adept that this issue may need to be addressed in some way in the future without costing the site to be penalized for having multiple pages with the same content just to support product quantities.
2) A slight modification of 1 is to present all available options but if the stock of any one option is empty then something is done to signify that. (Ie, typical shoe example, if all size 8s are gone, then depending on other options chosen either do not show size 8 in the list or otherwise show it but identify that it is out-of-stock.)
3) Step through selection of each attribute, presenting or hiding the attribute options out-of-stock, with the next attribute available to select after the previous attribute has been selected. (This is how dynamic dropdowns has been written and is of the style sequenced dropdown, but only displays in-stock options and does not offer display of out-of-stock options.) Stock quantities could maybe mean something going down this path, but what would be the rules of display while building the product? If it were the least quantity, then would show out-of-stock if one variant is, if it is least but not the out-of-stock number, then won't it be wrong when coming to that last desired attribute? My suggestion would be if the quantity is shown, to display some alternate message until the last attribute is selected. I'm currently working on a modification to this style to show sequenced dropdowns but to allow the possibility of showing what options are not available in stock.
4) Display every possible combination, selection of any one updates the display of the others regarding availability of the product on those other attributes. (This requires some method of "auto-updating" such as javascript, jQuery or ajax calls) the display of quantity available adjacent to an unselected option is not very meaningful in this setup unless some sort of multi-table graphical display is provided. Instead my suggestion would be to show the total available for a selected combination under this setup be a single quantity identifier updated based on each attribute selection with any previously selected attribute that becomes out-of-stock as a result of a new selection be highlighted or something to alert the customer.

There may be some things I have left off of each/any of the above options, but the important thing is to recognize that it is in this aspect that so many things have gone wrong in times past with SBA. No one plan has been fully developed per se (though right now if dynamic dropdowns is installed without the provided template file and with correction to one of the define files then this plugin works... Seems that there are still some minor issues to resolve for various special cases, but it works..). It is my thought that each of the above would be implemented in this single plugin with control by options in the configuration area... 

Also unless there is some overriding priority, my plan is to continue on with the modification/development of the sequenced dropdown that would allow presentation of out-of-stock attributes, then transition to a similar selection as provided in section 4. The first two probably could be quickly put together, but seem the least beneficial to the overall product... Any/all input is welcome. I use this plugin for a very narrow needed product, but have had a vision of it's broader use for over two years when I first started using ZC. Didn't understand ZC enough then to be able to put much towards it, but now that a concerted effort has been made to get this fully functional, I'm glad to be a part of it.

**Comment by mc12345678** [comment]
I pushed a version of SBA that will at the base level handle multi-attribute products, but at the moment there is no extra information associated with the individual entries. (ie, no custom id information, no quantities presented), but the quantity check upon addition to the cart still occurs, so its not "lawless". :)

**Comment by jeking928** [comment]
In re-reading you 'decisions/functions/options', items 3 and 4 would be much more beneficial than 1 and 2. I think 4 is the better approach. I'd suggest making the quantity available optional and out of stock attributes grayed out to indicate it is available just not at the moment.  As you show, showing quantity along he way would be of little use and mis-leading.

**Comment by mc12345678** [comment]
Option 4 is the ideal goal.  Option 3 is partially implemented by Dynamic Dropdowns (currently limited in that it does not visually offer information about any one attribute selection being disabled, ie. there is no greyed out option that indicates out-of-stock, it just simply isn't displayed). First thing I'm working on (started a while back but we had some other issues herein to address, so had stopped work on that part) is to have the cascade dropdowns present a listing for an attribute that is out-of-stock, and increase the amount of information displayable as supported by SBA (ie. customid, description, whatever). For clarity sake, in the cascade dropdowns configuration, I'm considering that if an option value that is out-of-stock that is not in the last option name group is selected will prevent further selection of additional dropdowns. The thought is/was that there is nothing to select in the subsequent dropdowns as there is nothing available so why display it if selection of another adjacent option value would provide the same result.  Hmm.. Think I've talked myself into the below based on the "points" I'm trying to make above.

Perhaps in the spirit of allowing display of out-of-stock option values that this option also be configurable. (Design with full capability, allow removal of some of the capability). Basically, the sequenced path option is to some extent fully dependent on what the database has been populated with for each selection. So my assertion above that an adjacent path would provide an equivalent selection "bank" is incorrect, and therefore at all times it should be possible to drill down to the last option name regardless of stock availability if the desire is to display out-of-stock selections.  Of course not to allow addition to the cart of that product, which could be limited by the last option name not allowing selection of an item in the list or some other action to reduce the customer dissatisfaction of trying to add an out-of-stock product to the cart.

**Comment by jeking928** [comment]
By George, I think you've got it.  That would be how I'd like to see it as well. I think it provides the necessary usability.

**Comment by mc12345678** [comment]
Take a look at the mc12345678_ZC154 branch... Dynamic Dropdowns with Sequenced dropdowns that should respect the admin configuration settings for the options provided there (Show product that is out-of-stock, etc...) I've implemented some error checking and notifications, but would say that additional suggestions are desired to take the capability further.  Still need to work out the logic for displaying all attribute selections allowing selection of any one that will update all of the others and when one of the items is out-of-stock to provide that information... Some of it has to do with if one of the options is/would have been available.  If not then how to handle the issue...

Anyways, Sequenced Dropdowns that display out-of-stock items is here but needs some touch-ups.

**Comment by jeking928** [comment]
I like it, lots of news stuff.  I am seeing an odd behavior.  I'm using my old friend Matrox G200 MMS. I've added stock for each of the six mixed attribute combinations.  With the Model attribute first, the message next to the option value is 'out of stock' This is incorrect.

If I change the sort order and put Memory first, out of stock does not appear.  Site is currently live at:
http://www.wheatonwebsiteservices.com/zen154/index.php?main_page=product_info&cPath=1_4&products_id=1

I'll do a more thorough review later today.

**Comment by mc12345678** [comment]
Check out the change that was made to includes/classes/pad_sba_sequenced_dropdowns.php.

Added a sort on the SELECT statement that is concatenated together to provide the result for the attributes_id comparison.

I did contemplate something else that seems to need to be addressed for further flexibility.  It seems that the "table" created for display of the attributes is actually not based on the SBA table at all.....  Meaning, right now it produces every variant that could possibly exist whether the SBA table is populated with every variant or not.  Ideally, the product options displayed to store visitors would only include the variants that have been chosen to be stocked (whether stock is 0 or not), not to force every possible variant to be populated...  Those two are/can be significantly different...

**Comment by jeking928** [comment]
I used the new includes/classes/pad_sba_sequenced_dropdowns.php but still get the 'out of stock' on the memory option.

**Comment by mc12345678** [comment]
Figured out what the problem is, now need to figure out how to resolve it. In the first section, the attributes are searched in the sba table using something like "4%" which means it is looking for 4 to start the list, of course if there is something that starts with 44, then that will return a "false" positive on the search, so either in the same single line it needs to search for any of the following, or the queries need to be broken up to provide results a little better:
Num
Num,%
%,Num,% or
%,Num

Those four scenarios will return a result that supports the desired "review". Otherwise need to do more work on the inner query that is not or is not easily supported through mysql and then feed that result into the outer query.

More to follow unless a solution is otherwise offered.

I was able to reproduce the "problem" which only identified the first attribute as out of stock, but did not prevent selecting the second attribute and adding the product to the cart. So is/was a "display" only problem fortunately. (Didn't think that was the case at first until I tested a little further.) Thanks for pointing that out. The blessings of testing. :)

**Comment by mc12345678** [comment]
Not sure how resource friendly it is, but research indicates that could actually or the 4 searches together with like statements. So from table x like Num or like Num,% or like %,Num,% or like %,Num where num is actually the results of the select query on the attributes table... Now to see if that value found once can be reused within the query without performing the query again... (Think it would reduce the load if that works...)

**Comment by mc12345678** [comment]
Fixed... Tried to find a better/more compact way to obtain the results, but I guess I save that for others to contemplate... I'm thinking that I might be able to run the query once and feed it back as a sort of array, but have to leave something for others to make improvement, right? :)

**Comment by jeking928** [comment]
Very nice fix and how considerate to save some work for someone else.  :)

**Comment by mc12345678** [comment]
1. Base attributes.php code has been modified to produce single versions of each option value within the option name when multiple attributes are associated with a product. This removes direct display of other information added through SBA (quantity, customid, etc.). 
2. To provide the extra data, Dynamic Dropdowns has been incorporated (with changes necessary for it to function properly), the use of Dynamic Dropdowns has been set to have switches to turn on/off the option entirely and to control use of the dynamic dropdown features of single/multiple attributes. 
3. Added a class for dynamix dropdowns to support display of out-of-stock variants as well as the additional information incorporated for display on variant selections using sequenced dropdowns.  Information is to be displayed on the last selection as before that point, no specific detailed information is available. One exception of waiting to display applicable information untill the last selection is out-of-stock information at a "higher" tier is available when all subselections are out of stock.
4. Display of out-of-stock product does not prevent further browsing of options available.

Based on the above, this issue is considered closed. Any issues with implementation of the above should be addressed by either a new issue or carried over to an existing related issue.
